[application]

name = "dioxus-starter"

default_platform = "desktop"

[web.app]

# HTML title tag content
title = "dioxus-starter"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["assets/tailwind.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

asset_dir = "assets"

[bundle]
# Bundle identifier
identifier = "pro.safwan.dioxus_starter"

# Bundle publisher
publisher = "Safwan Abdulghani"

# Bundle copyright
copyright = "Copyright (c) Safwan.pro 2025. All rights reserved."

# Bundle short description
short_description = "Safwan.pro"

# Bundle icon
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]

# Bundle resources
# resources = ["assets/*"]

[bundle.windows]
tsp = true
icon_path = "assets/favicon.ico"
allow_downgrades = true
binary_name = "Dioxus-Starter"
webview_install_mode = { OfflineInstaller = { silent = false } }
